# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import toxicblend.toxicblend_pb2 as toxicblend__pb2


class ToxicBlendServiceStub(object):
    """A gRPC service protocol used by ToxicBlend - a Blender addon written in Rust.
    https://github.com/eadf/toxicblend.rs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.execute = channel.unary_unary(
                '/toxicblend.ToxicBlendService/execute',
                request_serializer=toxicblend__pb2.Command.SerializeToString,
                response_deserializer=toxicblend__pb2.Reply.FromString,
                )


class ToxicBlendServiceServicer(object):
    """A gRPC service protocol used by ToxicBlend - a Blender addon written in Rust.
    https://github.com/eadf/toxicblend.rs
    """

    def execute(self, request, context):
        """Executes a over-the-net gRPC call. Usually used by the blender addon to send a few vertices to
        be processed by the toxicblend server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToxicBlendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'execute': grpc.unary_unary_rpc_method_handler(
                    servicer.execute,
                    request_deserializer=toxicblend__pb2.Command.FromString,
                    response_serializer=toxicblend__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'toxicblend.ToxicBlendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ToxicBlendService(object):
    """A gRPC service protocol used by ToxicBlend - a Blender addon written in Rust.
    https://github.com/eadf/toxicblend.rs
    """

    @staticmethod
    def execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/toxicblend.ToxicBlendService/execute',
            toxicblend__pb2.Command.SerializeToString,
            toxicblend__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
