[package]
name = "toxicblend"
version = "0.0.12"
authors = ["eadf"]
edition = "2018"
description = "gRPC based Blender-addons. WIP"
readme = "README.md"
repository = "https://github.com/eadf/toxicblend.rs"
license = "AGPL-3.0"
keywords = ["blender-addon", "centerline", "voronoi", "Lindenmayer_3d"]
exclude = [
    "img/*",
    "idea/*",
    ".github/*",
]

[dependencies]
tonic = "0.5"
prost = "0.8"
ahash = "0.7"
tokio = { version = "1.6", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0"
linestring = {version="0.6.3",default-features=false,features=["cgmath", "rayon"]}
centerline = "0.5.2"
yabf = {version="0.2",default-features=false}
boostvoronoi = "0.9.2"
rayon = "1.5"
smallvec = "^1.6.1"
cgmath = "0.18"
itertools = "0.10"
building-blocks = { version="0.6", default-features = false, features = ["mesh"]}
logos = "0.12"
async-scoped = { version = "0.7", features = ["use-tokio"] }

[[bin]]
name = "toxicblend_server"
path = "src/server.rs"

[build-dependencies]
tonic-build = "0.5"
version_check = "0.9"

[profile.release]
lto = true

[badges]
maintenance = { status = "actively-developed" }
