[package]
name = "toxicblend"
version = "0.0.6"
authors = ["eadf"]
edition = "2018"
description = "Client/Server application for Blender. WIP"
readme = "README.md"
repository = "https://github.com/eadf/toxicblend.rs"
license = "AGPL-3.0"
keywords = ["blender-addon", "centerline", "voronoi"]
exclude = [
    "img/*",
    "idea/*"
]

[dependencies]
tonic = "^0.4.2"
prost = "^0.7.0"
fnv = "^1.0.7"
ahash = "^0.7.2"
tokio = { version = "^1.6.0", features = ["macros", "rt-multi-thread"] }
thiserror = "^1.0.24"
linestring = {version="^0.3.0",default-features=false,features=["impl-cgmath", "impl-rayon"]}
centerline = "^0.3.0"
yabf = {version="^0.1.1",default-features=false}
boostvoronoi = "^0.8.1"
rayon = "^1.5.0"
smallvec = "^1.6.1"
cgmath = "^0.18.0"
itertools = "^0.10.0"
rand = "0.8"
building-blocks = { version="^0.6.0", default-features = false, features = ["mesh", "sdfu"]}
# This requires https://github.com/eadf/dcc-lsystem, branch: data-renderer, to be downloaded to ../dcc-lsystem
dcc-lsystem = { path="../dcc-lsystem/dcc-lsystem", default-features=false}

[[bin]]
name = "toxicblend_server"
path = "src/server.rs"

[build-dependencies]
tonic-build = "^0.4.2"

[profile.release]
lto = true

