[package]
name = "toxicblend"
version = "0.0.1"
authors = ["eadf"]
edition = "2018"
description = "work in progress"
readme = "README.md"
repository = "https://github.com/eadf/toxicblend.rs"
license = "AGPL-3.0"
#keywords = ["geometry", "intersection", "douglas-peucker", "visvalingam-whyatt"]

[dependencies]
