name: Clippy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install nightly
        run : rustup toolchain install nightly nightly-2021-04-25
      - name: install clippy
        run : rustup +nightly component add --toolchain nightly-2021-04-25 clippy
      - name: install rustfmt
        run: rustup +nightly component add --toolchain nightly-2021-04-25 rustfmt
      - name: Run clippy
        run: cargo +nightly clippy
