name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download deps
        run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev
      - uses: actions/checkout@v2
      - name: install nightly
        run: rustup toolchain install nightly-2021-04-25
      - name: install rustfmt
        run: rustup +nightly component add --toolchain nightly-2021-04-25 rustfmt
      - name: Build
        run: cargo +nightly --toolchain nightly-2021-04-25 build --verbose
      - name: Run tests
        run: cargo +nightly --toolchain nightly-2021-04-25 test --verbose

